// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "stimulus"
import Chart from 'stimulus-chartjs'

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

const application = Application.start()
application.register('chart', Chart)
